ALTER TABLE loads ADD COLUMN IF NOT EXISTS assigned_to_user_id BIGINT;
ALTER TABLE loads ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMPTZ;
ALTER TABLE loads ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;
ALTER TABLE loads ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE loads ADD COLUMN IF NOT EXISTS epod_url TEXT;
