ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS funded_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS funded_by_user_id BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS released_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS released_by_user_id BIGINT REFERENCES app_users(id) ON DELETE SET NULL;
