import { useEffect, useState, useMemo } from "react";
import { toast } from "sonner";
import { MessageSquare, FileText, CheckCircle, Clock, TruckIcon, AlertCircle, Flag, Users, DollarSign, FileCheck, Activity, X } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Card } from '../components/ui/card';
import { ScrollArea } from '../components/ui/scroll-area';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '../components/ui/dialog';
import {
  fetchContracts,
  acceptContract,
  rejectContract,
  type ContractRecord,
} from '../api/marketplace';
import { fetchLoadById, type LoadDetail } from '../lib/api';
import { useNavigate } from 'react-router-dom';

interface ContractWithLoad extends ContractRecord {
  load?: LoadDetail | null;
  shipperName?: string;
}

export default function HaulerContractsTab() {
  const [contracts, setContracts] = useState<ContractWithLoad[]>([]);
  const [loading, setLoading] = useState(false);
  const [selectedContract, setSelectedContract] = useState<ContractWithLoad | null>(null);
  const [showViewDialog, setShowViewDialog] = useState(false);
  const [showAcceptDialog, setShowAcceptDialog] = useState(false);
  const [showRejectDialog, setShowRejectDialog] = useState(false);
  const navigate = useNavigate();

  const negotiationContracts = useMemo(() => 
    contracts.filter(c => ['DRAFT', 'SENT'].includes(c.status.toUpperCase())),
    [contracts]
  );
  
  const confirmedContracts = useMemo(() => 
    contracts.filter(c => c.status.toUpperCase() === 'ACCEPTED'),
    [contracts]
  );

  const receivedContracts = useMemo(() => 
    negotiationContracts.filter(c => c.status.toUpperCase() === 'SENT'),
    [negotiationContracts]
  );

  const totalEarnings = useMemo(() => {
    return confirmedContracts.reduce((total, contract) => {
      if (contract.price_amount) {
        const amount = Number(contract.price_amount);
        if (contract.price_type === 'per-mile') {
          return total + (amount * 200); // Assuming 200 miles average
        }
        return total + amount;
      }
      return total;
    }, 0);
  }, [confirmedContracts]);

  const loadContracts = async () => {
    try {
      setLoading(true);
      const resp = await fetchContracts();
      const contractsWithLoads = await Promise.all(
        resp.items.map(async (contract) => {
          let load: LoadDetail | null = null;
          try {
            load = await fetchLoadById(Number(contract.load_id));
          } catch (err) {
            console.warn('Failed to load load details:', err);
          }
          return { ...contract, load };
        })
      );
      setContracts(contractsWithLoads);
    } catch (err: any) {
      toast.error(err?.message ?? "Failed to load contracts");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadContracts();
  }, []);

  const handleViewContract = (contract: ContractWithLoad) => {
    setSelectedContract(contract);
    setShowViewDialog(true);
  };

  const handleAccept = async () => {
    if (!selectedContract) return;
    try {
      await acceptContract(selectedContract.id);
      toast.success("Contract accepted successfully! You can now add this load to your trips.");
      setShowAcceptDialog(false);
      setShowViewDialog(false);
      setSelectedContract(null);
      await loadContracts();
      // Navigate to trips after a short delay
      setTimeout(() => {
        navigate('/hauler/trips');
      }, 1000);
    } catch (err: any) {
      toast.error(err?.message ?? "Failed to accept contract");
    }
  };

  const handleReject = async () => {
    if (!selectedContract) return;
    try {
      await rejectContract(selectedContract.id);
      toast.success("Contract rejected");
      setShowRejectDialog(false);
      setShowViewDialog(false);
      setSelectedContract(null);
      await loadContracts();
    } catch (err: any) {
      toast.error(err?.message ?? "Failed to reject contract");
    }
  };

  if (loading) {
    return <div className="p-6 text-sm text-gray-500">Loading contracts…</div>;
  }

  return (
    <div className="p-6 md:p-8">
      <div className="mb-8">
        <h1 className="mb-2 text-2xl font-semibold">My Contracts</h1>
        <p className="text-sm text-gray-500">
          Once contract is generated by shipper and confirmed by you, you can add this load to your trips
        </p>
      </div>

      {/* 4 Analytics Boxes */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <Card className="p-4 hover:shadow-lg transition-shadow cursor-pointer">
          <div className="flex items-center justify-between mb-3">
            <div className="w-10 h-10 rounded-lg flex items-center justify-center" style={{ backgroundColor: '#e8f7f1' }}>
              <Users className="w-5 h-5" style={{ color: '#42b883' }} />
            </div>
          </div>
          <div className="text-2xl mb-1">{contracts.length}</div>
          <div className="text-sm text-gray-600">Total Contracts</div>
          <div className="text-xs text-gray-500 mt-2">All contracts</div>
        </Card>

        <Card className="p-4 hover:shadow-lg transition-shadow cursor-pointer">
          <div className="flex items-center justify-between mb-3">
            <div className="w-10 h-10 rounded-lg flex items-center justify-center bg-blue-100">
              <DollarSign className="w-5 h-5 text-blue-600" />
            </div>
          </div>
          <div className="text-2xl mb-1">${(totalEarnings / 1000).toFixed(1)}K</div>
          <div className="text-sm text-gray-600">Total Earnings</div>
          <div className="text-xs text-gray-500 mt-2">From confirmed contracts</div>
        </Card>

        <Card className="p-4 hover:shadow-lg transition-shadow cursor-pointer">
          <div className="flex items-center justify-between mb-3">
            <div className="w-10 h-10 rounded-lg flex items-center justify-center bg-green-100">
              <FileCheck className="w-5 h-5 text-green-600" />
            </div>
          </div>
          <div className="text-2xl mb-1">{confirmedContracts.length}</div>
          <div className="text-sm text-gray-600">Confirmed Contracts</div>
          <div className="text-xs text-gray-500 mt-2">Ready for trips</div>
        </Card>

        <Card className="p-4 hover:shadow-lg transition-shadow cursor-pointer">
          <div className="flex items-center justify-between mb-3">
            <div className="w-10 h-10 rounded-lg flex items-center justify-center bg-orange-100">
              <Activity className="w-5 h-5 text-orange-600" />
            </div>
          </div>
          <div className="text-2xl mb-1">{negotiationContracts.length}</div>
          <div className="text-sm text-gray-600">Active Negotiations</div>
          <div className="text-xs text-gray-500 mt-2">In progress</div>
        </Card>
      </div>

      {/* Action Required Notification */}
      {receivedContracts.length > 0 && (
        <Card className="p-5 mb-8 border-orange-200 bg-orange-50">
          <div className="flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-orange-500 mt-0.5" />
            <div className="flex-1">
              <p className="text-sm text-orange-700">
                <strong>Action Required:</strong> You have {receivedContracts.length} contract(s) awaiting your response. Please review and accept or reject them.
              </p>
            </div>
          </div>
        </Card>
      )}

      {/* Important Message */}
      <Card className="p-5 mb-8 border-blue-200 bg-blue-50">
        <div className="flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-blue-500 mt-0.5" />
          <div className="flex-1">
            <p className="text-sm text-blue-700">
              <strong>Important:</strong> Please review all contract terms carefully before accepting. Once accepted, the contract will be added to your available trips.
            </p>
          </div>
        </div>
      </Card>

      {/* Two Box Layout for Negotiations */}
      <div className="mb-10">
        <h2 className="text-xl font-semibold mb-6">Negotiations</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Box 1: Awaiting Your Response */}
          <Card className="p-6 border-2 flex flex-col" style={{ borderColor: '#42b883', minHeight: '600px' }}>
            <h3 className="mb-5 flex items-center gap-2 flex-shrink-0 text-lg font-semibold">
              <Clock className="w-5 h-5" style={{ color: '#42b883' }} />
              Awaiting Your Response ({receivedContracts.length})
            </h3>
            <ScrollArea className="flex-1 pr-2">
              <div className="space-y-4">
                {receivedContracts.length > 0 ? (
                  receivedContracts.map((contract) => (
                    <Card key={contract.id} className="p-5 hover:shadow-md transition-all">
                      <div className="flex items-start gap-4">
                        <div className="w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0" style={{ backgroundColor: '#e8f7f1' }}>
                          <FileText className="w-6 h-6" style={{ color: '#42b883' }} />
                        </div>
                        
                        <div className="flex-1 min-w-0">
                          <div className="flex items-start justify-between gap-2 mb-3">
                            <div className="flex-1 min-w-0">
                              <h4 className="text-base font-semibold mb-2 truncate">Contract #{contract.id}</h4>
                              {contract.load && (
                                <div className="flex items-center gap-2 text-xs text-gray-600 flex-wrap">
                                  <span className="flex items-center gap-1">
                                    <TruckIcon className="w-3 h-3" />
                                    {contract.load.pickup_location} → {contract.load.dropoff_location}
                                  </span>
                                  {contract.load.species && (
                                    <>
                                      <span>•</span>
                                      <span className="capitalize">{contract.load.species}</span>
                                    </>
                                  )}
                                  {contract.load.quantity && (
                                    <>
                                      <span>•</span>
                                      <span>{contract.load.quantity} head</span>
                                    </>
                                  )}
                                </div>
                              )}
                            </div>
                            <Badge className="px-2 py-1 text-xs" style={{ backgroundColor: '#ef4444', color: 'white' }}>
                              New
                            </Badge>
                          </div>

                          <div className="flex items-center justify-between gap-4 mb-4">
                            <div>
                              <p className="text-xs text-gray-500 mb-1">Contract Price</p>
                              <p className="text-lg font-semibold" style={{ color: '#42b883' }}>
                                ${contract.price_amount ? Number(contract.price_amount).toLocaleString() : '0.00'}{contract.price_type === 'per-mile' ? '/mi' : ''}
                              </p>
                            </div>
                            <div className="text-right">
                              <p className="text-xs text-gray-500 mb-1">Sent</p>
                              <p className="text-xs text-gray-600">
                                {contract.sent_at ? new Date(contract.sent_at).toLocaleDateString() : '—'}
                              </p>
                            </div>
                          </div>

                          <div className="flex gap-3 flex-wrap">
                            <Button
                              onClick={() => handleViewContract(contract)}
                              variant="outline"
                              className="px-4 py-2 text-sm flex items-center gap-1"
                            >
                              <FileText className="w-4 h-4" />
                              View Contract
                            </Button>
                            <Button
                              onClick={() => {
                                setSelectedContract(contract);
                                setShowAcceptDialog(true);
                              }}
                              className="px-4 py-2 text-sm"
                              style={{ backgroundColor: '#42b883', color: 'white' }}
                            >
                              <CheckCircle className="w-4 h-4 mr-1" />
                              Accept
                            </Button>
                            <Button
                              onClick={() => {
                                setSelectedContract(contract);
                                setShowRejectDialog(true);
                              }}
                              variant="outline"
                              className="px-4 py-2 text-sm text-red-600 border-red-600 hover:bg-red-50"
                            >
                              <X className="w-4 h-4 mr-1" />
                              Reject
                            </Button>
                          </div>
                        </div>
                      </div>
                    </Card>
                  ))
                ) : (
                  <div className="text-center py-8 text-gray-500 text-sm">
                    No contracts awaiting your response
                  </div>
                )}
              </div>
            </ScrollArea>
          </Card>

          {/* Box 2: Drafts (if any) */}
          <Card className="p-6 border-2 border-gray-300 flex flex-col" style={{ minHeight: '600px' }}>
            <h3 className="mb-5 flex items-center gap-2 flex-shrink-0 text-lg font-semibold">
              <Clock className="w-5 h-5 text-gray-600" />
              Draft Contracts ({negotiationContracts.filter(c => c.status.toUpperCase() === 'DRAFT').length})
            </h3>
            <ScrollArea className="flex-1 pr-2">
              <div className="space-y-4">
                {negotiationContracts.filter(c => c.status.toUpperCase() === 'DRAFT').length > 0 ? (
                  negotiationContracts.filter(c => c.status.toUpperCase() === 'DRAFT').map((contract) => (
                    <Card key={contract.id} className="p-5 hover:shadow-md transition-all bg-gray-50">
                      <div className="flex items-start gap-4">
                        <div className="w-12 h-12 rounded-full bg-gray-300 flex items-center justify-center flex-shrink-0">
                          <FileText className="w-6 h-6 text-gray-600" />
                        </div>
                        
                        <div className="flex-1 min-w-0">
                          <div className="flex items-start justify-between gap-2 mb-3">
                            <div className="flex-1 min-w-0">
                              <h4 className="text-base font-semibold mb-2 truncate">Contract #{contract.id}</h4>
                              {contract.load && (
                                <div className="flex items-center gap-2 text-xs text-gray-600 flex-wrap">
                                  <span className="flex items-center gap-1">
                                    <TruckIcon className="w-3 h-3" />
                                    {contract.load.pickup_location} → {contract.load.dropoff_location}
                                  </span>
                                </div>
                              )}
                            </div>
                            <Badge variant="outline" className="px-2 py-1 text-xs">
                              Draft
                            </Badge>
                          </div>

                          <p className="text-xs text-gray-400 mt-2">
                            Waiting for shipper to send contract...
                          </p>
                        </div>
                      </div>
                    </Card>
                  ))
                ) : (
                  <div className="text-center py-8 text-gray-500 text-sm">
                    No draft contracts
                  </div>
                )}
              </div>
            </ScrollArea>
          </Card>
        </div>
      </div>

      {/* Confirmed Contracts */}
      <div className="mb-10 pt-6">
        <div className="flex items-center justify-between mb-6">
          <h3 className="flex items-center gap-2 text-xl font-semibold">
            <CheckCircle className="w-5 h-5 text-green-600" />
            Confirmed Contracts ({confirmedContracts.length})
          </h3>
        </div>
        
        <div className="space-y-5">
          {confirmedContracts.map((contract) => (
            <Card key={contract.id} className="p-6 hover:shadow-md transition-all border-green-200 bg-green-50">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-full bg-green-200 flex items-center justify-center flex-shrink-0">
                  <CheckCircle className="w-6 h-6 text-green-600" />
                </div>
                
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2 mb-3">
                    <div className="flex-1 min-w-0">
                      <h4 className="text-base font-semibold mb-2 truncate">Contract #{contract.id}</h4>
                      {contract.load && (
                        <div className="flex items-center gap-2 text-xs text-gray-600 flex-wrap">
                          <span className="flex items-center gap-1">
                            <TruckIcon className="w-3 h-3" />
                            {contract.load.pickup_location} → {contract.load.dropoff_location}
                          </span>
                          {contract.load.species && (
                            <>
                              <span>•</span>
                              <span className="capitalize">{contract.load.species}</span>
                            </>
                          )}
                          {contract.load.quantity && (
                            <>
                              <span>•</span>
                              <span>{contract.load.quantity} head</span>
                            </>
                          )}
                        </div>
                      )}
                    </div>
                    <Badge className="px-2 py-1 text-xs" style={{ backgroundColor: '#42b883', color: 'white' }}>
                      Confirmed
                    </Badge>
                  </div>

                  <div className="flex items-center justify-between gap-4 mb-4">
                    <div>
                      <p className="text-xs text-gray-500 mb-1">Agreed Price</p>
                      <p className="text-lg font-semibold text-green-600">
                        ${contract.price_amount ? Number(contract.price_amount).toLocaleString() : '0.00'}{contract.price_type === 'per-mile' ? '/mi' : ''}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs text-gray-500 mb-1">Confirmed</p>
                      <p className="text-xs text-gray-600">
                        {contract.accepted_at ? new Date(contract.accepted_at).toLocaleDateString() : '—'}
                      </p>
                    </div>
                  </div>

                  <div className="flex gap-3 flex-wrap">
                    <Button
                      onClick={() => handleViewContract(contract)}
                      variant="outline"
                      className="px-5 py-2.5 text-sm flex items-center gap-1"
                    >
                      <FileText className="w-4 h-4" />
                      View Contract
                    </Button>
                    <Button
                      onClick={() => navigate('/hauler/trips')}
                      variant="outline"
                      className="px-5 py-2.5 text-sm flex items-center gap-1"
                    >
                      <TruckIcon className="w-4 h-4" />
                      View Trips
                    </Button>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </div>

      {/* View Contract Dialog */}
      {selectedContract && (
        <Dialog open={showViewDialog} onOpenChange={setShowViewDialog}>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Contract #{selectedContract.id}</DialogTitle>
              <DialogDescription>
                Contract Status: <Badge className="capitalize">{selectedContract.status.toLowerCase()}</Badge>
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4">
              {selectedContract.load && (
                <>
                  <div>
                    <h4 className="font-semibold mb-2">Route</h4>
                    <p className="text-sm text-gray-600">
                      {selectedContract.load.pickup_location} → {selectedContract.load.dropoff_location}
                    </p>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    {selectedContract.load.species && (
                      <div>
                        <p className="text-xs text-gray-500 mb-1">Species</p>
                        <p className="text-sm font-medium capitalize">{selectedContract.load.species}</p>
                      </div>
                    )}
                    {selectedContract.load.quantity && (
                      <div>
                        <p className="text-xs text-gray-500 mb-1">Quantity</p>
                        <p className="text-sm font-medium">{selectedContract.load.quantity} head</p>
                      </div>
                    )}
                    {selectedContract.load.weight && (
                      <div>
                        <p className="text-xs text-gray-500 mb-1">Weight</p>
                        <p className="text-sm font-medium">{Number(selectedContract.load.weight).toLocaleString()} kg</p>
                      </div>
                    )}
                    {selectedContract.load.pickup_date && (
                      <div>
                        <p className="text-xs text-gray-500 mb-1">Pickup Date</p>
                        <p className="text-sm font-medium">
                          {new Date(selectedContract.load.pickup_date).toLocaleDateString()}
                        </p>
                      </div>
                    )}
                  </div>
                </>
              )}
              <div>
                <h4 className="font-semibold mb-2">Contract Terms</h4>
                <div className="space-y-2">
                  <div>
                    <p className="text-xs text-gray-500">Price</p>
                    <p className="text-lg font-semibold" style={{ color: '#42b883' }}>
                      ${selectedContract.price_amount ? Number(selectedContract.price_amount).toLocaleString() : '0.00'}{selectedContract.price_type === 'per-mile' ? '/mile' : ' total'}
                    </p>
                  </div>
                  {selectedContract.payment_method && (
                    <div>
                      <p className="text-xs text-gray-500">Payment Method</p>
                      <p className="text-sm">{selectedContract.payment_method}</p>
                    </div>
                  )}
                  {selectedContract.payment_schedule && (
                    <div>
                      <p className="text-xs text-gray-500">Payment Schedule</p>
                      <p className="text-sm">{selectedContract.payment_schedule}</p>
                    </div>
                  )}
                </div>
              </div>
              {selectedContract.contract_payload && Object.keys(selectedContract.contract_payload).length > 0 && (
                <div>
                  <h4 className="font-semibold mb-3">Contract Details</h4>
                  <div className="space-y-4">
                    {(() => {
                      const payload = selectedContract.contract_payload as Record<string, any>;
                      const sections: JSX.Element[] = [];
                      
                      // Basic Contract Info
                      if (payload.contractType || payload.contractDuration) {
                        sections.push(
                          <div key="basic" className="border-b pb-3">
                            <h5 className="text-sm font-semibold mb-2 text-gray-700">Basic Information</h5>
                            <div className="grid grid-cols-2 gap-3">
                              {payload.contractType && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Contract Type</p>
                                  <p className="text-sm font-medium capitalize">{payload.contractType.replace(/-/g, ' ')}</p>
                                </div>
                              )}
                              {payload.contractDuration && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Duration</p>
                                  <p className="text-sm font-medium capitalize">{payload.contractDuration.replace(/-/g, ' ')}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }
                      
                      // Payment Terms
                      if (payload.paymentMethod || payload.paymentSchedule || payload.depositRequired) {
                        sections.push(
                          <div key="payment" className="border-b pb-3">
                            <h5 className="text-sm font-semibold mb-2 text-gray-700">Payment Terms</h5>
                            <div className="grid grid-cols-2 gap-3">
                              {payload.paymentMethod && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Payment Method</p>
                                  <p className="text-sm font-medium capitalize">{payload.paymentMethod.replace(/-/g, ' ')}</p>
                                </div>
                              )}
                              {payload.paymentSchedule && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Payment Schedule</p>
                                  <p className="text-sm font-medium capitalize">{payload.paymentSchedule.replace(/-/g, ' ')}</p>
                                </div>
                              )}
                              {payload.depositRequired && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Deposit Required</p>
                                  <p className="text-sm font-medium capitalize">{payload.depositRequired === 'yes' ? 'Yes' : 'No'}</p>
                                </div>
                              )}
                              {payload.depositPercentage && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Deposit Percentage</p>
                                  <p className="text-sm font-medium">{payload.depositPercentage}%</p>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }
                      
                      // Trip Details
                      if (payload.pickupDate || payload.deliveryDate || payload.estimatedDistance || payload.routeType) {
                        sections.push(
                          <div key="trip" className="border-b pb-3">
                            <h5 className="text-sm font-semibold mb-2 text-gray-700">Trip Details</h5>
                            <div className="grid grid-cols-2 gap-3">
                              {payload.pickupDate && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Pickup Date</p>
                                  <p className="text-sm font-medium">
                                    {payload.pickupDate} {payload.pickupTime ? `at ${payload.pickupTime}` : ''}
                                  </p>
                                </div>
                              )}
                              {payload.deliveryDate && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Delivery Date</p>
                                  <p className="text-sm font-medium">
                                    {payload.deliveryDate} {payload.deliveryTime ? `at ${payload.deliveryTime}` : ''}
                                  </p>
                                </div>
                              )}
                              {payload.estimatedDistance && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Estimated Distance</p>
                                  <p className="text-sm font-medium">{payload.estimatedDistance} miles</p>
                                </div>
                              )}
                              {payload.routeType && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Route Type</p>
                                  <p className="text-sm font-medium capitalize">{payload.routeType}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }
                      
                      // Animal Welfare
                      if (payload.restStopsRequired || payload.temperatureMonitoring || payload.ventilationRequired || payload.waterAccessRequired) {
                        sections.push(
                          <div key="welfare" className="border-b pb-3">
                            <h5 className="text-sm font-semibold mb-2 text-gray-700">Animal Welfare</h5>
                            <div className="grid grid-cols-2 gap-3">
                              {payload.restStopsRequired && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Rest Stops Required</p>
                                  <p className="text-sm font-medium capitalize">{payload.restStopsRequired === 'yes' ? 'Yes' : 'No'}</p>
                                </div>
                              )}
                              {payload.restStopInterval && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Rest Stop Interval</p>
                                  <p className="text-sm font-medium">{payload.restStopInterval} hours</p>
                                </div>
                              )}
                              {payload.temperatureMonitoring && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Temperature Monitoring</p>
                                  <p className="text-sm font-medium capitalize">{payload.temperatureMonitoring === 'yes' ? 'Yes' : 'No'}</p>
                                </div>
                              )}
                              {payload.temperatureRange && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Temperature Range</p>
                                  <p className="text-sm font-medium">{payload.temperatureRange}°F</p>
                                </div>
                              )}
                              {payload.ventilationRequired && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Ventilation Required</p>
                                  <p className="text-sm font-medium capitalize">{payload.ventilationRequired === 'yes' ? 'Yes' : 'No'}</p>
                                </div>
                              )}
                              {payload.waterAccessRequired && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Water Access Required</p>
                                  <p className="text-sm font-medium capitalize">{payload.waterAccessRequired === 'yes' ? 'Yes' : 'No'}</p>
                                </div>
                              )}
                              {payload.feedingSchedule && (
                                <div className="col-span-2">
                                  <p className="text-xs text-gray-500 mb-1">Feeding Schedule</p>
                                  <p className="text-sm font-medium">{payload.feedingSchedule}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }
                      
                      // Insurance & Liability
                      if (payload.insuranceCoverage || payload.liabilityLimit || payload.cargoInsurance) {
                        sections.push(
                          <div key="insurance" className="border-b pb-3">
                            <h5 className="text-sm font-semibold mb-2 text-gray-700">Insurance & Liability</h5>
                            <div className="grid grid-cols-2 gap-3">
                              {payload.insuranceCoverage && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Insurance Coverage</p>
                                  <p className="text-sm font-medium capitalize">{payload.insuranceCoverage}</p>
                                </div>
                              )}
                              {payload.liabilityLimit && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Liability Limit</p>
                                  <p className="text-sm font-medium">${Number(payload.liabilityLimit).toLocaleString()}</p>
                                </div>
                              )}
                              {payload.cargoInsurance && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Cargo Insurance</p>
                                  <p className="text-sm font-medium capitalize">{payload.cargoInsurance === 'yes' ? 'Yes' : 'No'}</p>
                                </div>
                              )}
                              {payload.additionalInsurance && (
                                <div className="col-span-2">
                                  <p className="text-xs text-gray-500 mb-1">Additional Insurance</p>
                                  <p className="text-sm font-medium">{payload.additionalInsurance}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }
                      
                      // Compliance & Documentation
                      if (payload.healthCertificates || payload.movementPermits || payload.dotCompliance || payload.animalWelfareCompliance) {
                        sections.push(
                          <div key="compliance" className="border-b pb-3">
                            <h5 className="text-sm font-semibold mb-2 text-gray-700">Compliance & Documentation</h5>
                            <div className="grid grid-cols-2 gap-3">
                              {payload.healthCertificates && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Health Certificates</p>
                                  <p className="text-sm font-medium capitalize">{payload.healthCertificates}</p>
                                </div>
                              )}
                              {payload.movementPermits && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Movement Permits</p>
                                  <p className="text-sm font-medium capitalize">{payload.movementPermits}</p>
                                </div>
                              )}
                              {payload.dotCompliance && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">DOT Compliance</p>
                                  <p className="text-sm font-medium capitalize">{payload.dotCompliance}</p>
                                </div>
                              )}
                              {payload.animalWelfareCompliance && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Animal Welfare Compliance</p>
                                  <p className="text-sm font-medium capitalize">{payload.animalWelfareCompliance}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }
                      
                      // Special Requirements
                      if (payload.specialHandling || payload.equipmentRequirements || payload.emergencyContact) {
                        sections.push(
                          <div key="special" className="border-b pb-3">
                            <h5 className="text-sm font-semibold mb-2 text-gray-700">Special Requirements</h5>
                            <div className="space-y-2">
                              {payload.specialHandling && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Special Handling</p>
                                  <p className="text-sm font-medium">{payload.specialHandling}</p>
                                </div>
                              )}
                              {payload.equipmentRequirements && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Equipment Requirements</p>
                                  <p className="text-sm font-medium">{payload.equipmentRequirements}</p>
                                </div>
                              )}
                              {payload.emergencyContact && (
                                <div className="grid grid-cols-2 gap-3">
                                  <div>
                                    <p className="text-xs text-gray-500 mb-1">Emergency Contact</p>
                                    <p className="text-sm font-medium">{payload.emergencyContact}</p>
                                  </div>
                                  {payload.emergencyPhone && (
                                    <div>
                                      <p className="text-xs text-gray-500 mb-1">Emergency Phone</p>
                                      <p className="text-sm font-medium">{payload.emergencyPhone}</p>
                                    </div>
                                  )}
                                </div>
                              )}
                              {payload.veterinarianOnCall && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Veterinarian On Call</p>
                                  <p className="text-sm font-medium">{payload.veterinarianOnCall}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }
                      
                      // Terms & Conditions
                      if (payload.cancellationPolicy || payload.lateFeePolicy || payload.disputeResolution || payload.forcemajeure) {
                        sections.push(
                          <div key="terms" className="border-b pb-3">
                            <h5 className="text-sm font-semibold mb-2 text-gray-700">Terms & Conditions</h5>
                            <div className="grid grid-cols-2 gap-3">
                              {payload.cancellationPolicy && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Cancellation Policy</p>
                                  <p className="text-sm font-medium capitalize">{payload.cancellationPolicy.replace(/-/g, ' ')}</p>
                                </div>
                              )}
                              {payload.lateFeePolicy && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Late Fee Policy</p>
                                  <p className="text-sm font-medium capitalize">{payload.lateFeePolicy === 'yes' ? 'Yes' : 'No'}</p>
                                </div>
                              )}
                              {payload.disputeResolution && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Dispute Resolution</p>
                                  <p className="text-sm font-medium capitalize">{payload.disputeResolution}</p>
                                </div>
                              )}
                              {payload.forcemajeure && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Force Majeure</p>
                                  <p className="text-sm font-medium capitalize">{payload.forcemajeure === 'yes' ? 'Yes' : 'No'}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }
                      
                      // Additional Notes
                      if (payload.additionalTerms || payload.specialInstructions) {
                        sections.push(
                          <div key="notes" className="pb-3">
                            <h5 className="text-sm font-semibold mb-2 text-gray-700">Additional Notes</h5>
                            <div className="space-y-2">
                              {payload.additionalTerms && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Additional Terms</p>
                                  <p className="text-sm font-medium">{payload.additionalTerms}</p>
                                </div>
                              )}
                              {payload.specialInstructions && (
                                <div>
                                  <p className="text-xs text-gray-500 mb-1">Special Instructions</p>
                                  <p className="text-sm font-medium">{payload.specialInstructions}</p>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }
                      
                      return sections.length > 0 ? sections : null;
                    })()}
                  </div>
                </div>
              )}
              {selectedContract.status.toUpperCase() === 'SENT' && (
                <div className="flex gap-2 pt-4">
                  <Button
                    onClick={() => {
                      setShowViewDialog(false);
                      setShowAcceptDialog(true);
                    }}
                    className="flex-1"
                    style={{ backgroundColor: '#42b883', color: 'white' }}
                  >
                    <CheckCircle className="w-4 h-4 mr-2" />
                    Accept Contract
                  </Button>
                  <Button
                    onClick={() => {
                      setShowViewDialog(false);
                      setShowRejectDialog(true);
                    }}
                    variant="outline"
                    className="flex-1 text-red-600 border-red-600 hover:bg-red-50"
                  >
                    <X className="w-4 h-4 mr-2" />
                    Reject Contract
                  </Button>
                </div>
              )}
            </div>
          </DialogContent>
        </Dialog>
      )}

      {/* Accept Confirmation Dialog */}
      <Dialog open={showAcceptDialog} onOpenChange={setShowAcceptDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Accept Contract</DialogTitle>
            <DialogDescription>
              Are you sure you want to accept this contract? Once accepted, it will be added to your trips.
            </DialogDescription>
          </DialogHeader>
          <div className="flex gap-2 justify-end pt-4">
            <Button variant="outline" onClick={() => setShowAcceptDialog(false)}>
              Cancel
            </Button>
            <Button
              onClick={handleAccept}
              style={{ backgroundColor: '#42b883', color: 'white' }}
            >
              Accept Contract
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Reject Confirmation Dialog */}
      <Dialog open={showRejectDialog} onOpenChange={setShowRejectDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Reject Contract</DialogTitle>
            <DialogDescription>
              Are you sure you want to reject this contract? This action cannot be undone.
            </DialogDescription>
          </DialogHeader>
          <div className="flex gap-2 justify-end pt-4">
            <Button variant="outline" onClick={() => setShowRejectDialog(false)}>
              Cancel
            </Button>
            <Button
              onClick={handleReject}
              variant="outline"
              className="text-red-600 border-red-600 hover:bg-red-50"
            >
              Reject Contract
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
